version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "vue"
        update-types: ["version-update:semver-major"]
      - dependency-name: "vuetify"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "deps(npm):"
    groups:
      vue-stack:
        patterns:
          - "vue*"
          - "vuetify*"
      build-tools:
        patterns:
          - "@vitejs/*"
          - "vite"
          - "eslint*"
          - "typescript*"

  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "weekly"
      day: "friday"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps(cargo):"
    ignore:
      - dependency-name: "tauri"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
    commit-message:
      prefix: "deps(actions):"