name: Build App
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: "npm"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies for Tauri
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libwebkit2gtk-4.1-dev \
            build-essential \
            curl \
            wget \
            file \
            libxdo-dev \
            libssl-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev

      - name: Install dependencies
        run: npm install

      - name: Build App
        run: npm run tauri build

      - name: Package Binary
        run: |
          cd src-tauri/target/release
          tar -czf ../../../rdp-connector-${{ github.ref_name }}.tar.gz rdp-connector
        shell: bash

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: rdp-connector
          path: rdp-connector-${{ github.ref_name }}.tar.gz

      - name: Upload Bundles
        uses: actions/upload-artifact@v4
        with:
          name: rdp-connector-bundles
          path: |
            src-tauri/target/release/bundle/**/*.deb
            src-tauri/target/release/bundle/**/*.rpm

  freerdp:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Build FreeRDP
        run: bash ${{ github.workspace }}/freerdp/build.sh

      - name: Package FreeRDP Binaries
        run: |
          cd freerdp
          tar -czf ../freerdp-bundle-${{ github.ref_name }}.tar.gz bin lib run-xfreerdp.sh
        shell: bash

      - name: Upload FreeRDP Archive
        uses: actions/upload-artifact@v4
        with:
          name: freerdp-archive
          path: freerdp-bundle-${{ github.ref_name }}.tar.gz

  release:
    needs: [build, freerdp]
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Download all artifacts
        uses: actions/download-artifact@v5
        with:
          path: ./artifacts

      - name: Extract release notes from CHANGELOG
        id: changelog
        run: |
          VERSION="${{ github.ref_name }}"
          awk "/^## $VERSION/{flag=1; next} /^## /{flag=0} flag" CHANGELOG.md >> RELEASE_NOTES.md || true

          if grep -q "## $VERSION" CHANGELOG.md; then
            echo "found_notes=true" >> $GITHUB_OUTPUT
          else
            echo "found_notes=false" >> $GITHUB_OUTPUT
          fi

      - name: Create GitHub Release (from CHANGELOG)
        if: steps.changelog.outputs.found_notes == 'true'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          body_path: RELEASE_NOTES.md
          files: ./artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub Release (auto-generated notes)
        if: steps.changelog.outputs.found_notes == 'false'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          files: ./artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
